services:

  broker:
    build: ./Server
    container_name: broker-${BROKER_ID}
    environment:
      BROKER_ID: "${BROKER_ID}"
      BROKER_PORT: "12345"
      UDP_PORT: "12346"
      PEERS: "${PEERS}"
      DRONE_TIMEOUT: "10"
      GANACHE_URL: "${GANACHE_URL}"   
    ports:
      - "12345:12345"
      - "12346:12346/udp"
    profiles: ["${BROKER_ID}"]

  drone-1:
    build: ./Actuators
    container_name: drone-${BROKER_ID}1
    environment:
      BROKER_ID: "${BROKER_ID}"
      PEERS: "${PEERS}"
      PORT: "12345"
    depends_on:
      - broker
    profiles: ["${BROKER_ID}"]

  drone-2:
    build: ./Actuators
    container_name: drone-${BROKER_ID}2
    environment:
      BROKER_ID: "${BROKER_ID}"
      PEERS: "${PEERS}"
      PORT: "12345"
    depends_on:
      - broker
    profiles: ["${BROKER_ID}"]

  radar:
    build: ./Sensors
    container_name: radar-${BROKER_ID}
    command: python -u sensor_radar.py
    environment:
      BROKER_HOST: broker-${BROKER_ID}
      BROKER_PORT: "12346"
      ZONA: "setor-${BROKER_ID}"
    depends_on:
      - broker
    profiles: ["${BROKER_ID}"]

  boia-1:
    build: ./Sensors
    container_name: boia-${BROKER_ID}1
    command: python -u sensor_boia.py
    environment:
      BROKER_HOST: broker-${BROKER_ID}
      BROKER_PORT: "12346"
    depends_on:
      - broker
    profiles: ["${BROKER_ID}"]

  boia-2:
    build: ./Sensors
    container_name: boia-${BROKER_ID}2
    command: python -u sensor_boia.py
    environment:
      BROKER_HOST: broker-${BROKER_ID}
      BROKER_PORT: "12346"
    depends_on:
      - broker
    profiles: ["${BROKER_ID}"]